name: Update README

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          MAX_LINES: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
